framework: triplet
text_backbone: bert-base-uncased
data_dir: ../../../msd-splits/dataset
arch: transformer
workers: 24
epochs: 100
warmup_epochs: 10
start_epoch: 0
batch_size: 32
world_size: 2
lr: 0.0001
min_lr: 1.0e-09
rank: 0
dist_url: tcp://localhost:12312
dist_backend: nccl
seed: null
gpu: 0
print_freq: 50
multiprocessing_distributed: true
duration: 9.91
sr: 16000
num_chunks: 3
mel_dim: 128
n_fft: 1024
win_length: 1024
frontend: cnn
mix_type: cf
audio_rep: mel
cos: true
attention_nlayers: 4
attention_ndim: 256
margin: 0.4
mlp_dim: 128
text_type: glove
text_rep: caption
distributed: true
text_dim: 300
audio_dim: 256
